In [1]:
#exercice1
import numpy as np

A = np.array ([ [3,1,5], [9, 8, -1], [110, 12 ,2] ])
B = np.array ([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])

C= A+B
print("A : ",A)
print("B : ",B)
print("A + B : ",C)

A :  [[  3   1   5]
 [  9   8  -1]
 [110  12   2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A + B :  [[ 11   0  13]
 [ 11   9   2]
 [128  14  34]]


In [2]:
#exercice 1 sans numpy
#without numpy
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [4]:
#exercice 2
import numpy as np

A = np.array ([ [3,1,5], [9, 8, -1], [110, 12 ,2] ])
B = np.array ([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])

C= A*B
print("A : \n",A)
print("B : \n",B)
print("A * B :\n ",C)

A :  [[  3   1   5]
 [  9   8  -1]
 [110  12   2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A * B :  [[  24   -1   40]
 [  18    8   -3]
 [1980   24   64]]


In [7]:
#exercice 3
def eststochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est stochastique
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s > 1:
            etat = False
            break
    return etat
 
 
def estbistochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est bistochastique
    if(eststochastique(P)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s > 1:
                etat = False
                break
    return etat
def vecteurstable(G, h):
    nl = len(G)  # nombre de lignes
    nc = len(G[0])  # nombre de colonnes
    etat = True
    if(eststochastique(G)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i]*G[i][j]
            if s != h[j]:
                etat = False
                break
    else:
        etat = False
    return etat

In [9]:
#exercice 4
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [18, 12, 2] ])
 
C = A.transpose()
 
print("A : \n", A)
print("Transposée de A : \n", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [18 12  2]]
Transposée de A : 
 [[ 3  9 18]
 [ 1  8 12]
 [ 5 -1  2]]
